# Document:
# http://simiki.org/docs/configuration.html

url: 
title: wiki
keywords: technology, machine learning, data mining, economics, accounting
description: A wiki website of wangyaoxu when I learned new knowledgy and technics.
author: wangyaoxu

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: yasimple_x2